site_name: CEU matters
repo_url: https://github.com/cambridge-ceu/CEU-matters/
edit_uri: ""
nav:
  - "   ": README.md
  - Chronicle:
    - 2025: 2025.md
    - 2024: 2024.md
    - 2023: 2023.md
    - 2022: 2022.md
    - 2021: 2021.md
    - 2020: 2020.md
    - Cambridge-Baker-Joint-Symposium.md
    - COVID-19: COVID-19.md
    - dpp.md
    - mhs.md
  - HDR(UK): HDR-UK.md
  - Schedules: schedules.md
  - Resources:
    - "Cardiovascular Epidemiology Unit": CEU.md
    - "Department of Public Health and Primary Care": DPHPC.md
    - "Victor Phillip Dahdaleh Heart and Lung Research Institute": VPD-HLRI.md
    - "Clinical School": CS.md
    - "University of Cambridge": UoC.md
    - "Student-Run Computing Facility":
        - Terminal: https://www.srcf.net/terminal/
        - Flask: Flask.md
        - c6: c6.md
        - Node.js: Node.md
        - WebServer: webserver.md
  - Channels: channels.md
  - Talks: talks.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - mermaid2
markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
